figure()
plot(out.simout.Time,out.simout.Data(:,1),"--",...
    "Color",lineStyles(1,:),"LineWidth",1.5); hold on;
plot(out.simout.Time,out.simout.Data(:,2),"-.",...
    "Color",lineStyles(2,:),"LineWidth",1.5);
plot(out.simout.Time,out.simout.Data(:,3),...
    "Color",lineStyles(3,:),"LineWidth",1.5); grid;
legend("$\omega=\omega_{e}=0.1$",...
    "$\omega=0.05;\omega_{e}=0.1$",...
    "$\omega=\omega_{e}=0.05$",...
    "Location", "southeast","Interpreter","Latex")
title("Time step response for all test cases")
xlabel("Time (s)"); ylabel("y")
hold off;