figure()
plot(out.N.Time,out.N.Data(:,1),...
    "Color",lineStyles(1,:),"LineWidth",1.5); hold on;
plot(out.N.Time,out.N.Data(:,2),...
    "Color",lineStyles(2,:),"LineWidth",1.5);
plot(out.N.Time,out.N.Data(:,3),...
    "Color",lineStyles(3,:),"LineWidth",1.5); grid;
legend("$N=0.2$","$N=1.0$","$N=2.0$",...
    "Interpreter","Latex","Location", "southeast")
title("Time step response varying N")
xlabel("Time (s)"); ylabel("y")