%% Plot
figure()
plot(r1,'LineWidth',1.2,...
         'color',lineStyles(1,:)), hold on;
plot(ones(size(theta(1,:)))*R1,':','LineWidth',1.2,...
         'color',lineStyles(1,:)),
plot(s0,'LineWidth',1.2,...
         'color',lineStyles(2,:)),
plot(ones(size(theta(1,:)))*S0,':','LineWidth',1.2,...
         'color',lineStyles(2,:)), 
plot(s1,'LineWidth',1.2,...
         'color',lineStyles(3,:)),
plot(ones(size(theta(1,:)))*S1,':','LineWidth',1.2,...
         'color',lineStyles(3,:)), 
plot(t0,'LineWidth',1.2,...
         'color',lineStyles(4,:)),
plot(ones(size(theta(1,:)))*T0,':','LineWidth',1.2,...
         'color',lineStyles(4,:)), 
hold off; grid;
ylabel(['$\hat{R}(t),\hat{S}(t),\hat{T}(t)$'],'Interpreter','Latex'),
xlabel('$t (s)$','Interpreter','Latex');
legend('$\hat{r}_1$','','$\hat{s}_0$','',...
        '$\hat{s}_1$','','$\hat{t}_0$','',...
        'Interpreter','Latex','Location', "best");