figure()
plot(out.a.Time,out.a.Data(:,1),...
    "Color",lineStyles(1,:),"LineWidth",1.5); hold on;
plot(out.a.Time,out.a.Data(:,2),...
    "Color",lineStyles(2,:),"LineWidth",1.5);
plot(out.a.Time,out.a.Data(:,3),...
    "Color",lineStyles(3,:),"LineWidth",1.5); grid;
legend("$a=0.5$","$a=1.0$","$a=4.0$",...
    "Interpreter","Latex","Location", "southeast")
title("Time step response varying a")
xlabel("Time (s)"); ylabel("y")